// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPMv_Et2d_vbvoc99SzCvXAHhcY5nHWJI',
    appId: '1:458397158619:web:7bf3bfc9263c009dec10fe',
    messagingSenderId: '458397158619',
    projectId: 'food-delivery-c58af',
    authDomain: 'food-delivery-c58af.firebaseapp.com',
    storageBucket: 'food-delivery-c58af.appspot.com',
    measurementId: 'G-RDBRWZM7M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3PVTY58nq70vARSsdCDd9zrmQmnNMYdE',
    appId: '1:458397158619:android:6a944fdab99a520eec10fe',
    messagingSenderId: '458397158619',
    projectId: 'food-delivery-c58af',
    storageBucket: 'food-delivery-c58af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYA4zMqJ0OC_5BBgQvfd7Jl6JI5mnkQd0',
    appId: '1:458397158619:ios:0f660660aa2385a7ec10fe',
    messagingSenderId: '458397158619',
    projectId: 'food-delivery-c58af',
    storageBucket: 'food-delivery-c58af.appspot.com',
    iosBundleId: 'com.example.privatilyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYA4zMqJ0OC_5BBgQvfd7Jl6JI5mnkQd0',
    appId: '1:458397158619:ios:0f660660aa2385a7ec10fe',
    messagingSenderId: '458397158619',
    projectId: 'food-delivery-c58af',
    storageBucket: 'food-delivery-c58af.appspot.com',
    iosBundleId: 'com.example.privatilyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPMv_Et2d_vbvoc99SzCvXAHhcY5nHWJI',
    appId: '1:458397158619:web:ec1a6818c395ff89ec10fe',
    messagingSenderId: '458397158619',
    projectId: 'food-delivery-c58af',
    authDomain: 'food-delivery-c58af.firebaseapp.com',
    storageBucket: 'food-delivery-c58af.appspot.com',
    measurementId: 'G-909M2GC638',
  );
}
