// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOmgMUPlUTh4KE7y0Li5ZKH_0S038OBs',
    appId: '1:935975375761:web:615968393e85598fb74030',
    messagingSenderId: '935975375761',
    projectId: 'billtech-6f3b1',
    authDomain: 'billtech-6f3b1.firebaseapp.com',
    storageBucket: 'billtech-6f3b1.appspot.com',
    measurementId: 'G-1Q147Q9MVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3HGQ8AtMYDkEEsHbBmC2MNF9eg-mwA2c',
    appId: '1:935975375761:android:89a5ecfbe03e70b5b74030',
    messagingSenderId: '935975375761',
    projectId: 'billtech-6f3b1',
    storageBucket: 'billtech-6f3b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQyrLDO1opmeYvKLDpIZJI9OPwZybMMV0',
    appId: '1:935975375761:ios:c6ae1772e6366f65b74030',
    messagingSenderId: '935975375761',
    projectId: 'billtech-6f3b1',
    storageBucket: 'billtech-6f3b1.appspot.com',
    iosClientId: '935975375761-di7muenjlpd62539g8h0cabnunt4f6ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.privatilyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQyrLDO1opmeYvKLDpIZJI9OPwZybMMV0',
    appId: '1:935975375761:ios:c6ae1772e6366f65b74030',
    messagingSenderId: '935975375761',
    projectId: 'billtech-6f3b1',
    storageBucket: 'billtech-6f3b1.appspot.com',
    iosClientId: '935975375761-di7muenjlpd62539g8h0cabnunt4f6ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.privatilyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOmgMUPlUTh4KE7y0Li5ZKH_0S038OBs',
    appId: '1:935975375761:web:576a03f4d3b68774b74030',
    messagingSenderId: '935975375761',
    projectId: 'billtech-6f3b1',
    authDomain: 'billtech-6f3b1.firebaseapp.com',
    storageBucket: 'billtech-6f3b1.appspot.com',
    measurementId: 'G-FPTK59SV62',
  );

}